name = "Applied Energistics 2"
filename = "appliedenergistics2-8.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3354/897/appliedenergistics2-8.4.0.jar"
hash-format = "murmur2"
hash = "3038217317"

[update]
[update.curseforge]
file-id = 3354897
project-id = 223794
