name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.23.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3468/666/ars_nouveau-1.16.5-1.23.11.jar"
hash-format = "murmur2"
hash = "3486668826"

[update]
[update.curseforge]
file-id = 3468666
project-id = 401955
