name = "Blood Magic "
filename = "BloodMagic-1.16.4-3.1.3-18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3452/124/BloodMagic-1.16.4-3.1.3-18.jar"
hash-format = "murmur2"
hash = "3062692822"

[update]
[update.curseforge]
file-id = 3452124
project-id = 224791
