name = "Building Gadgets"
filename = "buildinggadgets-1.16.5-3.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3498/508/buildinggadgets-1.16.5-3.8.2.jar"
hash-format = "murmur2"
hash = "3980463159"

[update]
[update.curseforge]
file-id = 3498508
project-id = 298187
