name = "Building Gadgets"
filename = "buildinggadgets-1.16.5-3.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3205/295/buildinggadgets-1.16.5-3.8.0.jar"
hash-format = "murmur2"
hash = "3456565023"

[update]
[update.curseforge]
file-id = 3205295
project-id = 298187
