name = "CC: Tweaked"
filename = "cc-tweaked-1.16.5-1.98.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3434/680/cc-tweaked-1.16.5-1.98.2.jar"
hash-format = "murmur2"
hash = "2562506460"

[update]
[update.curseforge]
file-id = 3434680
project-id = 282001
