name = "Compact Machines"
filename = "compactmachines-4.0.0-beta.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3229/196/compactmachines-4.0.0-beta.2.jar"
hash-format = "murmur2"
hash = "3360947371"

[update]
[update.curseforge]
file-id = 3229196
project-id = 224218
