name = "Controlling"
filename = "Controlling-7.0.0.27.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3501/319/Controlling-7.0.0.27.jar"
hash-format = "murmur2"
hash = "1142186317"

[update]
[update.curseforge]
file-id = 3501319
project-id = 250398
