name = "Controlling"
filename = "Controlling-7.0.0.24.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3434/370/Controlling-7.0.0.24.jar"
hash-format = "murmur2"
hash = "323854253"

[update]
[update.curseforge]
file-id = 3434370
project-id = 250398
