name = "Create"
filename = "create-mc1.16.5_v0.3.2f.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3499/718/create-mc1.16.5_v0.3.2f.jar"
hash-format = "murmur2"
hash = "2050102413"

[update]
[update.curseforge]
file-id = 3499718
project-id = 328085
