name = "Dynamic View"
filename = "dynviewdist-2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/883/dynviewdist-2.0.jar"
hash-format = "murmur2"
hash = "2102439104"

[update]
[update.curseforge]
file-id = 3358883
project-id = 366140
