name = "Dynamic Trees"
filename = "DynamicTrees-1.16.5-0.10.0-Beta24.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/224/DynamicTrees-1.16.5-0.10.0-Beta24.jar"
hash-format = "murmur2"
hash = "3318898680"

[update]
[update.curseforge]
file-id = 3414224
project-id = 252818
