name = "Flux Networks"
filename = "FluxNetworks-1.16.5-6.1.7.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3285/556/FluxNetworks-1.16.5-6.1.7.12.jar"
hash-format = "murmur2"
hash = "1182115578"

[update]
[update.curseforge]
file-id = 3285556
project-id = 248020
