name = "Halogen"
filename = "sodium-forge-2.9.10+rev.ea6353c.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3410/21/sodium-forge-2.9.10+rev.ea6353c.jar"
hash-format = "murmur2"
hash = "2620665428"

[update]
[update.curseforge]
file-id = 3410021
project-id = 491233
