name = "iChunUtil"
filename = "iChunUtil-1.16.5-10.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3346/209/iChunUtil-1.16.5-10.4.1.jar"
hash-format = "murmur2"
hash = "1991337855"

[update]
[update.curseforge]
file-id = 3346209
project-id = 229060
