name = "Immersive Petroleum"
filename = "ImmersivePetroleum-1.16.5-3.3.0-6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3454/143/ImmersivePetroleum-1.16.5-3.3.0-6.jar"
hash-format = "murmur2"
hash = "3348380834"

[update]
[update.curseforge]
file-id = 3454143
project-id = 268250
