name = "Infernal Expansion"
filename = "infernal-expansion-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3421/482/infernal-expansion-2.2.0.jar"
hash-format = "murmur2"
hash = "1783870737"

[update]
[update.curseforge]
file-id = 3421482
project-id = 395078
