name = "Infernal Expansion"
filename = "infernal-expansion-2.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3487/698/infernal-expansion-2.3.2.jar"
hash-format = "murmur2"
hash = "3937989984"

[update]
[update.curseforge]
file-id = 3487698
project-id = 395078
