name = "Jade ğŸ”"
filename = "Jade-1.16.4-2.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3467/445/Jade-1.16.4-2.8.0.jar"
hash-format = "murmur2"
hash = "3753507984"

[update]
[update.curseforge]
file-id = 3467445
project-id = 324717
