name = "Just Enough Items (JEI)"
filename = "jei-1.16.5-7.7.1.121.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3438/494/jei-1.16.5-7.7.1.121.jar"
hash-format = "murmur2"
hash = "3158079338"

[update]
[update.curseforge]
file-id = 3438494
project-id = 238222
