name = "Kotlin for Forge"
filename = "kotlinforforge-1.15.1-obf.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3452/303/kotlinforforge-1.15.1-obf.jar"
hash-format = "murmur2"
hash = "1677492753"

[update]
[update.curseforge]
file-id = 3452303
project-id = 351264
