name = "Mekanism"
filename = "Mekanism-1.16.5-10.0.21.448.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3206/392/Mekanism-1.16.5-10.0.21.448.jar"
hash-format = "murmur2"
hash = "3390446425"

[update]
[update.curseforge]
file-id = 3206392
project-id = 268560
