name = "MmmMmmMmmMmm"
filename = "MmmMmmMmmMmm-1.16.5-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3473/5/MmmMmmMmmMmm-1.16.5-1.3.1.jar"
hash-format = "murmur2"
hash = "3534794908"

[update]
[update.curseforge]
file-id = 3473005
project-id = 225738
