name = "More Red Computercraft Integration"
filename = "morered_computercraft_integration-1.16.5-1.0.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3336/580/morered_computercraft_integration-1.16.5-1.0.0.0.jar"
hash-format = "murmur2"
hash = "3068453343"

[update]
[update.curseforge]
file-id = 3336580
project-id = 490403
