name = "Obfuscate"
filename = "obfuscate-0.6.2-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3336/21/obfuscate-0.6.2-1.16.3.jar"
hash-format = "murmur2"
hash = "2136839324"

[update]
[update.curseforge]
file-id = 3336021
project-id = 289380
