name = "Patchouli"
filename = "Patchouli-1.16.4-53.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/118/Patchouli-1.16.4-53.2.jar"
hash-format = "murmur2"
hash = "1640373126"

[update]
[update.curseforge]
file-id = 3459118
project-id = 306770
