name = "Phi (Psi addon)"
filename = "Phi-1.16-1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3456/712/Phi-1.16-1.7.jar"
hash-format = "murmur2"
hash = "326697623"

[update]
[update.curseforge]
file-id = 3456712
project-id = 476728
