name = "Placebo"
filename = "Placebo-1.16.5-4.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3536/806/Placebo-1.16.5-4.6.1.jar"
hash-format = "murmur2"
hash = "239807166"

[update]
[update.curseforge]
file-id = 3536806
project-id = 283644
