name = "Project: Vibrant Journeys"
filename = "projectvibrantjourneys-1.16.5-3.2.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3468/243/projectvibrantjourneys-1.16.5-3.2.10.jar"
hash-format = "murmur2"
hash = "3410786210"

[update]
[update.curseforge]
file-id = 3468243
project-id = 300297
