name = "Quark"
filename = "Quark-r2.4-321.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3538/744/Quark-r2.4-321.jar"
hash-format = "murmur2"
hash = "4281538317"

[update]
[update.curseforge]
file-id = 3538744
project-id = 243121
