name = "Scorge"
filename = "Scorge-3.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3276/638/Scorge-3.1.3.jar"
hash-format = "murmur2"
hash = "3055856884"

[update]
[update.curseforge]
file-id = 3276638
project-id = 471286
