name = "Serene Seasons"
filename = "SereneSeasons-1.16.5-4.0.1.121-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3429/973/SereneSeasons-1.16.5-4.0.1.121-universal.jar"
hash-format = "murmur2"
hash = "2040601117"

[update]
[update.curseforge]
file-id = 3429973
project-id = 291874
