name = "Simple Storage Network"
filename = "SimpleStorageNetwork-1.16.5-1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3476/575/SimpleStorageNetwork-1.16.5-1.5.0.jar"
hash-format = "murmur2"
hash = "154747691"

[update]
[update.curseforge]
file-id = 3476575
project-id = 268495
