name = "Thermal Foundation"
filename = "thermal_foundation-1.16.5-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3412/300/thermal_foundation-1.16.5-1.3.2.jar"
hash-format = "murmur2"
hash = "2482344754"

[update]
[update.curseforge]
file-id = 3412300
project-id = 222880
