name = "YUNG's API (Forge)"
filename = "YungsApi-1.16.4-Forge-12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3412/585/YungsApi-1.16.4-Forge-12.jar"
hash-format = "murmur2"
hash = "2028424798"

[update]
[update.curseforge]
file-id = 3412585
project-id = 421850
